import base64
import hashlib
import hmac
from typing import Callable, List, Optional, Tuple

import httpx

from agents.code_analysis import get_code_review_for_code

GITHUB_API = "https://api.github.com"

# File extensions we can analyze and their language names for the LLM prompt
EXTENSION_MAP = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".jsx": "javascript",
    ".tsx": "typescript",
    ".java": "java",
    ".cpp": "cpp",
    ".c": "c",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".cs": "csharp",
    ".swift": "swift",
    ".kt": "kotlin",
}

MAX_FILES_PER_EVENT = 8     # max files analyzed per push/PR (keeps response time sane)
MAX_FILE_BYTES = 80_000     # skip files larger than ~80 KB


# ── Signature verification ─────────────────────────────────────────────────────

def verify_signature(payload_bytes: bytes, sig_header: str, secret: str) -> bool:
    """Verify that the webhook payload was signed by GitHub using our secret."""
    if not sig_header.startswith("sha256="):
        return False
    expected = hmac.new(secret.encode(), payload_bytes, hashlib.sha256).hexdigest()
    received = sig_header[len("sha256="):]
    return hmac.compare_digest(expected, received)


# ── GitHub API helpers ─────────────────────────────────────────────────────────

def _api_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_pr_changed_files(owner: str, repo: str, pr_number: int, token: str) -> List[dict]:
    """Return list of file objects (filename, status) changed in a PR."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/files"
    with httpx.Client(timeout=15) as client:
        resp = client.get(url, headers=_api_headers(token), params={"per_page": 100})
        resp.raise_for_status()
        return resp.json()


def fetch_file_content(owner: str, repo: str, path: str, ref: str, token: str) -> Optional[str]:
    """Fetch the content of a single file at a specific commit ref via the GitHub Contents API."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}"
    with httpx.Client(timeout=15) as client:
        resp = client.get(url, headers=_api_headers(token), params={"ref": ref})
        if resp.status_code != 200:
            return None
        data = resp.json()
        if data.get("encoding") != "base64":
            return None
        raw = base64.b64decode(data["content"])
        if len(raw) > MAX_FILE_BYTES:
            return None  # too large for the LLM context
        try:
            return raw.decode("utf-8")
        except UnicodeDecodeError:
            return None  # binary file


def post_pr_review(owner: str, repo: str, pr_number: int, commit_sha: str, body: str, token: str):
    """Post a review comment on a Pull Request."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    payload = {"commit_id": commit_sha, "body": body, "event": "COMMENT"}
    with httpx.Client(timeout=15) as client:
        resp = client.post(url, headers=_api_headers(token), json=payload)
        resp.raise_for_status()


def post_commit_comment(owner: str, repo: str, commit_sha: str, body: str, token: str):
    """Post a comment directly on a commit."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/commits/{commit_sha}/comments"
    with httpx.Client(timeout=15) as client:
        resp = client.post(url, headers=_api_headers(token), json={"body": body})
        resp.raise_for_status()


# ── File selection helpers ─────────────────────────────────────────────────────

def _file_ext(path: str) -> str:
    return ("." + path.rsplit(".", 1)[-1].lower()) if "." in path.split("/")[-1] else ""


def _language(path: str) -> str:
    return EXTENSION_MAP.get(_file_ext(path), "text")


def _is_supported(path: str) -> bool:
    return _file_ext(path) in EXTENSION_MAP


# ── Comment builder ────────────────────────────────────────────────────────────

def _build_comment(file_reviews: List[Tuple[str, str]], skipped: List[str]) -> str:
    lines = [
        "## 🤖 CodeOptimizer — Automated Review\n",
        f"Analyzed **{len(file_reviews)}** file(s).",
    ]
    if skipped:
        lines.append(f"Skipped **{len(skipped)}** file(s) "
                     f"(unsupported type, binary, or too large): "
                     f"`{'`, `'.join(skipped)}`")
    lines.append("\n---\n")

    for filename, review in file_reviews:
        lines.append(f"<details>")
        lines.append(f"<summary>📄 <b>{filename}</b> — click to expand</summary>\n")
        lines.append(review)
        lines.append(f"\n</details>\n")

    lines.append("---")
    lines.append("*Generated by [CodeOptimizer](https://github.com/AtishayJain71/CodeOptimizer)*")
    return "\n".join(lines)


# ── Core analysis runner ───────────────────────────────────────────────────────

def _analyze_and_post(
    owner: str,
    repo: str,
    changed_files: List[str],
    ref: str,
    token: str,
    post_fn: Callable[[str], None],
):
    """
    Given a list of changed file paths and a commit ref:
      1. Filter to supported code files
      2. Fetch each file's content from GitHub
      3. Run code analysis
      4. Call post_fn with the formatted review comment
    """
    code_files = [f for f in changed_files if _is_supported(f)][:MAX_FILES_PER_EVENT]
    skipped = [f for f in changed_files if not _is_supported(f)]

    file_reviews: List[Tuple[str, str]] = []

    for path in code_files:
        content = fetch_file_content(owner, repo, path, ref, token)
        if content is None:
            skipped.append(path)
            continue

        lang = _language(path)
        result = get_code_review_for_code(content, lang)
        review_text = result.get("__inline__", "No review generated.")
        file_reviews.append((path, review_text))

    if not file_reviews:
        return  # nothing reviewable — don't post an empty comment

    body = _build_comment(file_reviews, skipped)
    post_fn(body)


# ── Public entry points (called from the webhook endpoint) ────────────────────

def handle_push(payload: dict, token: str):
    """Process a GitHub push event."""
    repo_full = payload["repository"]["full_name"]
    owner, repo = repo_full.split("/", 1)
    head_sha = (payload.get("head_commit") or {}).get("id", "")

    if not head_sha:
        return

    # Collect all added + modified files across every commit in the push
    changed: List[str] = []
    seen = set()
    for commit in payload.get("commits", []):
        for f in commit.get("added", []) + commit.get("modified", []):
            if f not in seen:
                seen.add(f)
                changed.append(f)

    _analyze_and_post(
        owner, repo, changed, head_sha, token,
        post_fn=lambda body: post_commit_comment(owner, repo, head_sha, body, token),
    )


def handle_pull_request(payload: dict, token: str):
    """Process a GitHub pull_request event (opened / synchronize / reopened)."""
    pr = payload["pull_request"]
    repo_full = payload["repository"]["full_name"]
    owner, repo = repo_full.split("/", 1)
    pr_number = pr["number"]
    head_sha = pr["head"]["sha"]

    files = get_pr_changed_files(owner, repo, pr_number, token)
    # Only look at added or modified files, not removed ones
    changed = [f["filename"] for f in files if f.get("status") != "removed"]

    _analyze_and_post(
        owner, repo, changed, head_sha, token,
        post_fn=lambda body: post_pr_review(owner, repo, pr_number, head_sha, body, token),
    )
